name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - run: pnpm i

      - run: pnpm docs:install

      - run: pnpm check

      - run: pnpm build

      - run: pnpm docs:build

      - run: pnpm test:coverage